apiVersion: v1
kind: Service
metadata:
  name: devops-ai-capstone
spec:
  selector:
    app: devops-ai-capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
